### ISSUE TITLE
[Question] How I can disable a session for a specific user?

### ISSUE THREAD

**Issue by lucianomlima** [smartlook/smartlook-react-native-sdk#1]
We have some admins users that don't need to record sessions.
Have some way to cancel recording for these users?

`UXCam` have a method like `cancelCurrentSession` that we can call when user is admin.

Thanks!

**Comment by adamblack** [comment]
Hi @lucianomlima ,

currently there is no functionality like that but we could create that at least on SDK side. Just few questions though:

1) Until implemented, would it be possible to start recording only once you know user is eligible?
2) If not, how long it takes for you to differentiate between regular and admin users? SDK has internal clocks handling uploads etc. so we would have to tweak that as well.

Thanks for the info!

**Comment by lucianomlima** [comment]
Hi @adamblack. Thanks for the quick response. For your questions:

1- Yeah, can be start later using user profile info but this not allow capture user issues related to onboarding, signin, signup or another logged off screen when admin info it's not available yet.
2- For a new user, I only can identify if he is a admin after signing. But I wish to capture issues with signup process or other screens that user it's not logged in.

Current implementation I follow is:
- call as soon as possible the SmartLook.init
- add user identity after successful login.

But I cannot disable and discard what was recorded after I know the user is admin.

It'll be a nice feature to allow cancel current session programmatically.
