### ISSUE TITLE
React native 0.60 with auto linking compatibility

### ISSUE THREAD

**Issue by adamgajzlerowicz** [smartlook/smartlook-react-native-sdk#10]
I am trying to install the package and use it with iOS on react native 0.60 but I am unable to get it linked correctly. Your "example" is running old version of RN. Can you please confirm that Smartlook is compatible with latest RN?

![image](https://user-images.githubusercontent.com/675615/64335725-b8662480-cfdb-11e9-888a-42c6da0ffaee.png)

![image](https://user-images.githubusercontent.com/675615/64335778-d2a00280-cfdb-11e9-9228-3426cab182c7.png)

**Comment by kennym** [comment]
Same problem here.

**Comment by pavel-kroh-smartlook** [comment]
New version of React Native was released today with updated linking (Cocoapods support.) that perhaps solve this issue. For details refer here: https://smartlook.github.io/docs/sdk/react-native/

**Comment by orafal-dev** [comment]
It did not fix the issue, I'm having the same on 0.61.2 RN.

Got the same error when following guide on your GH page.

Do you need separate plan for mobile app (got web already) ?

**Comment by pavel-kroh-smartlook** [comment]
Hi @rafalolszewski94 - mobile and web plans are separated, but check with our sales what the current options.

As for the technical issues, I will look into it, maybe RN changed something again between 0.60 and 0.61. Pretty annoying to be frank.

**Comment by kennym** [comment]
Issue fixed in 0.20.0
