### ISSUE TITLE
Some hard fixed code on iOS generate some warnings during build

### ISSUE THREAD

**Issue by lucianomlima** [smartlook/smartlook-react-native-sdk#11]
<img alt="ios-build-log" src="https://user-images.githubusercontent.com/1580205/64389975-46adcb00-d01b-11e9-9458-c7654c99a6aa.png">

**Comment by pavel-kroh-smartlook** [comment]
Hi, we are aware about this, but did not find a way to work it around yet. It is annoying but harmless. According to our investigations this happens when DSYM file is generated in DEBUG configuration (which is not usually the case, but is eg., recommended by Fabric Crashlytic).
