### ISSUE TITLE
iOS link error: Failed to get dependency config

### ISSUE THREAD

**Issue by iLyxa3D** [smartlook/smartlook-react-native-sdk#12]
macOS
node: v12.1.1
react-native: 2.0.1 / 0.59.9
smartlook-react-native-wrapper@0.15.0

`$ npm install smartlook-react-native-wrapper --save`   **ok**
`$ react-native link smartlook-react-native-wrapper`   **error**

`Error: Cannot find module '/Users/admin/Documents/[projectname]/node_modules/smartlook-react-native-wrapp/package.json'`
..but real name of the folder is "node_modules\smartlook-react-native-wrapp**er**"  -- missing last 2 characters.

This lead to linking error. Renaming the folder temporary fix the problem.

**Comment by pavel-kroh-smartlook** [comment]
Hi, we looked into it, cannot reproduce and also we could not find this typo in the code... will continue in searching...

**Comment by pavel-kroh-smartlook** [comment]
New version of React Native was released today with updated linking (Cocoapods support.) that perhaps solve this issue. For details refer here: https://smartlook.github.io/docs/sdk/react-native/
