### ISSUE TITLE
null is not an object (evaluating 'SmartlookBridge.init) on app launch

### ISSUE THREAD

**Issue by prnthh** [smartlook/smartlook-react-native-sdk#13]
I followed the instructions from [here](https://www.npmjs.com/package/smartlook-react-native-wrapper) to do the initial setup.

The app builds and deploys without a problem, but on app launch, I see the red crash dialog that says 'null is not an object (evaluating 'SmartlookBridge.init')'

 I am facing this issue on Android, with React Native version 0.59.5.

**Comment by elirangoshen** [comment]
I'm facing this issue on ios.
Os 12.2
react native 0.60.4
smart-look-react-native-wrapper 0.17.0

also i didnt use react-native link because it wont work in ios due to auto linking. but i added the framework

**Comment by Jendyy** [comment]
same problem (ios)

**Comment by pavel-kroh-smartlook** [comment]
@elirangoshen  For iOS on RN 0.6.0+, please check the new Smartlook RN bridge version that was just released. It implements new cocoapods/base linking https://github.com/smartlook/smartlook-react-native-bridge. Generally, the error on iOS means that the `Smartlook.framework` is not properly added to the Xcode project (something Cocoapods should handle now).
