### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by kennym** [smartlook/smartlook-react-native-sdk#16]
Smartlook-react-native-wrapper: 0.17.0

java.util.ConcurrentModificationException
    LinkedHashMap.java:757 java.util.LinkedHashMap$LinkedHashIterator.nextNode
    LinkedHashMap.java:780 java.util.LinkedHashMap$LinkedKeyIterator.next
    SourceFile:185 com.smartlook.sdk.smartlook.d.g.a
    SourceFile:73 com.smartlook.sdk.smartlook.d.g.a
    SourceFile:62 com.smartlook.sdk.smartlook.analytics.b.a.a
    SourceFile:288 com.smartlook.sdk.smartlook.c.b
    SourceFile:1272 com.smartlook.sdk.smartlook.Smartlook.track
    RNSmartlookModule.java:123 com.smartlook.sdk.RNSmartlookModule.track
    Method.java:-2 java.lang.reflect.Method.invoke
    JavaMethodWrapper.java:371 com.facebook.react.bridge.JavaMethodWrapper.invoke
    JavaModuleWrapper.java:150 com.facebook.react.bridge.JavaModuleWrapper.invoke
    NativeRunnable.java:-2 com.facebook.react.bridge.queue.NativeRunnable.run
    Handler.java:873 android.os.Handler.handleCallback
    Handler.java:99 android.os.Handler.dispatchMessage
    MessageQueueThreadHandler.java:26 com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
    Looper.java:193 android.os.Looper.loop
    MessageQueueThreadImpl.java:225 com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run
    Thread.java:764 java.lang.Thread.run

**Comment by kennym** [comment]
We speculate that we are passing a big payload to smartlook and that it blows up there. In any case, that should be handled gracefully.

**Comment by adamblack** [comment]
Should be ok in new version. In case of any issues, please create new thread or you can also contact us on Discord: https://discord.gg/SbEt98m
