### ISSUE TITLE
Session is being recorded even if app is in background

### ISSUE THREAD

**Issue by kennym** [smartlook/smartlook-react-native-sdk#17]
Smartlook keeps recording even after the user has put the app in background for more than a minute. Isn't this supposed to be handled by the wrapper library?

**Comment by adamblack** [comment]
Should be ok in new version. In case of any issues, please create new thread or you can also contact us on Discord: https://discord.gg/SbEt98m

**Comment by panteleymonchukcreator** [comment]
I have `0.26.0` version of package. 
Still have same issue. When turn off an application, sessions still with status `in progress` and close session only after 30 min maybe.
@adamblack is it normal behavior?
