### ISSUE TITLE
Create @types/smartlook-react-native-wrapper for TypeScript compatibility

### ISSUE THREAD

**Issue by BelfDev** [smartlook/smartlook-react-native-sdk#19]
Many React Native projects are nowadays also using TypeScript. I think many of your clients would benefit from creating a simple ".d.ts" file to bridge the static methods to TypeScript. 

I'm currently integrating SmartLook for a client and, if it interests you, I can create the bridge for you guys.

Cheers!

**Comment by dkoprowski** [comment]
Hi any update about typings?

**Comment by BelfDev** [comment]
@dkoprowski I can't find their source code anymore, but here are the typings I wrote for my client:

https://gist.github.com/BelfDev/513ca0ea57f9e6c5be933754a07b0a5d

Just place it in your project's root directory. I hope it helps! Happy coding :)

**Comment by dkoprowski** [comment]
Thank you @BelfDev! I was thinking about Smartlook company to add those typings to package - it becomes a standard for packages in JS world and everyone benefits from it.

**Comment by BelfDev** [comment]
@dkoprowski for sure! I should've opened a PR for them before. In the meantime, that gist should get you covered.

Cheers!

**Comment by adamblack** [comment]
Hi @BelfDev , @dkoprowski ,

this feature is in our backlog however I cannot give you exact ETA since it is not a top priority for us currently.
