### ISSUE TITLE
Installation via Pods for iOS Development

### ISSUE THREAD

**Issue by rudyryk** [smartlook/smartlook-react-native-sdk#2]
> Breaking changes: iOS SDK is no longer available via Pods but is provided as a bundle in the npm package - integration steps are described in the documentation mentioned above

But... why? :)

Generally specifying dependencies via Podfile results in more reliable build process for React Native / iOS.

**Comment by pavel-kroh-smartlook** [comment]
Our experience is the opposite. When the integration was via Cocoapods, we got regularly complaints that "it does not work, help". At the end, we decided to focus on our product, not on continual tweaking of 3rd party packaging service (Cocoapods) configuration, and use a straightforward solution that we have better control over and that works.

**Comment by rudyryk** [comment]
@pavel-kroh-smartlook Internet is full of pain on "React/RCTBridge.h not found" because RN build process contains on-fly tweaks. One day build could just show Heisenbug (one time it builds another time not). With Cocoapods we can have at least static configuration (without on-fly code generation) and understandable errors if they are.

**Comment by rudyryk** [comment]
Just recently re-assembled all the project piece by piece moving to Cocoapods because it just stopped building with usual `npm install` and `react-native link`. Total clean up also didn't work. But this is only our/my experience of course.
