### ISSUE TITLE
Request: Add support for Expo

### ISSUE THREAD

**Issue by jrobber** [smartlook/smartlook-react-native-sdk#20]
You have react-native support, which is awesome.  If you added support for expo (https://expo.io/) you'd open up a bunch more potential customers.

**Comment by adamblack** [comment]
Hi @jrobber ,

thanks for a tip for an improvement. Will let you know ETA once we do some research what would have to be done on our side. :]

**Comment by jrobber** [comment]
Thanks @adamblack as far as I can tell there are no session replay tools that work on expo.  We'll be your first customers, and I'd be happy to post word in the forums for you to let others know you're supported on expo now.

I'd also be happy to contribute if I can, or be a beta tester.

**Comment by pavel-kroh-smartlook** [comment]
[Expo Documentation](https://docs.expo.io/versions/v36.0.0/introduction/faq/) -> Common Questions -> "How do I add custom native code to my Expo project?" reads:

_"Managed Expo projects don't support custom native code, including third-party libraries which require custom native components. In a managed project, you only write JavaScript."_

Smartlook SDK is indeed _custom native code_, and must be for obvious technologic reasons.

cc: @SenNeonoveNoci

**Comment by pavel-kroh-smartlook** [comment]
PS: You could indeed use Smartlook SKD in `eject`ed native projects if you include it as a native library there. You will however not get access to Smartlook SDK API methods from Expo this way as custom native code bridging is explicitly not supported in Expo.
