### ISSUE TITLE
Usage of deprecated UIWebView on iOS will cause App Store rejection

### ISSUE THREAD

**Issue by evelant** [smartlook/smartlook-react-native-sdk#21]
I'm getting a warning on submission to Apple that usage of the deprecated UIWebView API will result in rejection from the App Store. Doing a quick search with `grep -r UIWebView node_modules/*` seems to indicate that smartlook-react-native-wrapper is the culprit using this API.

Is there a plan to remove the deprecated API before apps start getting rejected? Smartlook is very useful and I'd hate to be forced to stop using it due to this.

**Comment by pavel-kroh-smartlook** [comment]
Hi Andrew, we only recently started calling a deprecate UIWebView API in order to support hiding sensitive data in embedded web views. However, in the light of this warning, I'll propose to drop supporting this functionality in the deprecated UIWebView and keep it on WKWebView only so we can remove the API calls that most likely cause this warning. We do not need UIWebView for anything in our SDK itself. cc: @Acro

**Comment by pavel-kroh-smartlook** [comment]
UIWebView API calls will be removed in the next version of iOS Smartlook SDK. However, the string will still be there (as it always was) for we need to check if some view is UIWebView. This however should not trigger App Store warning nor cause app rejection.

**Comment by pavel-kroh-smartlook** [comment]
`UIWebView` API calls removed from SDK. See: https://github.com/smartlook/smartlook-ios-sdk#126---2019-12-02

**Comment by forward-S** [comment]
Hi! We have been using last version, "smartlook-react-native-wrapper": "^0.22.0", but still getting this deprecated API warning.
We see you solve this warning on iOS native SDK.
When would you plan to upgrade react-native sdk?

I would appreciate it if you explain what we can change inside the module to avoid this warning.

**Comment by pavel-kroh-smartlook** [comment]
Hi @forward-S , Smartlook SDK is referred from the react bridge as a Cocoapods dependency, so updating pods should always download the latest version.

**Comment by Welook4** [comment]
I'm facing the same issue, I have in my project:
- Smartlook (1.2.7)
- smartlook-react-native-bridge (0.22.0)

The only part with a "UIWebView" reference is: 
RNSmartlook line 138
![image](https://user-images.githubusercontent.com/53534814/73086848-2a1e0c80-3eb0-11ea-854d-ad4bee84439e.png)

**Comment by pavel-kroh-smartlook** [comment]
Darn it... hopefully finally solved in the latest release today.
