### ISSUE TITLE
v0.22.0 fails to build on iOS with linker error

### ISSUE THREAD

**Issue by evelant** [smartlook/smartlook-react-native-sdk#22]
Trying to build with smartlook-react-native-wrapper on iOS my build is failing with the following error

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Smartlook", referenced from:
      objc-class-ref in RNSmartlook.o
  "_SLNavigationTypeExit", referenced from:
      ___46-[RNSmartlook trackNavigationEvent:direction:]_block_invoke in RNSmartlook.o
  "_SLNavigationTypeEnter", referenced from:
      ___46-[RNSmartlook trackNavigationEvent:direction:]_block_invoke in RNSmartlook.o
  "_SLSetupOptionFramerateKey", referenced from:
      ___31-[RNSmartlook setup:framerate:]_block_invoke in RNSmartlook.o
      ___48-[RNSmartlook setupAndStartRecording:framerate:]_block_invoke in RNSmartlook.o
ld: symbol(s) not found for architecture x86_64
```

I'm on RN 0.61 and the Smartlook sdk is installed via cocoa pods per the docs. I've tried cleaning my build dir in Xcode without success.

**Comment by pavel-kroh-smartlook** [comment]
Just tested the following steps and got working Smartlook in a RN (0.61.5) project

```bash
# create project
npx react-native init RNTest01
cd RNTest01/

# insttall Smartlook plugin
npm install smartlook-react-native-wrapper --save

#edit Podfile to add pod 'smartlook-react-native-bridge' as described in documentation
open ios/Podfile 

# install Smartlook pods
cd ios
pod install
# should print out:
#    Installing Smartlook (1.2.6)
#    Installing smartlook-react-native-bridge (0.22.0)

# now add Smartlook initialisation in App.js:
# var Smartlook = require("smartlook-react-native-wrapper"); 
# Smartlook.setupAndStartRecording("API_KEY");
open ../App.js

open RNTest01.xcworkspace

# run the Xcode project
```

**Comment by evelant** [comment]
I think this is related to having use_frameworks! in the pod file. I made some changes and was able to remove use_frameworks! and now it builds for me. Others may not be able to do so however.

**Comment by pavel-kroh-smartlook** [comment]
I see. Not sure we can do anything with this on our side. The dependance on a combination of various supporting 3rd party frameworks like Cocoapods and React Native is always fragile and unpredictable if deterministic at all, see eg. here: https://github.com/smartlook/smartlook-ios-sdk/issues/11

**Comment by filipef101** [comment]
I had to put this in react-native.config.js
```
module.exports = {
  project: {
    ios: {},
    android: {}, // grouped into "project"
  },
  assets: [
    './assets/fonts/',
  ],
  dependencies: {
    "smartlook-react-native-wrapper": {
      platforms: {
        ios: null
      }
    }
  }
};

```

And add to podFile
`  pod 'smartlook-react-native-bridge', :podspec => '../node_modules/smartlook-react-native-wrapper/ios/smartlook-react-native-bridge.podspec'`

**Comment by filipef101** [comment]
Maybe the docs should mention how to suport the lib with the use_native_modules!
Or just change the podspec to the root as it should be, which is the real issue

**Comment by pavel-kroh-smartlook** [comment]
Bridge structure updated, podspec moved to root of the bridge, hopefully solving this issue.

https://github.com/smartlook/smartlook-react-native-sdk/blob/master/README.md#0230---2020-01-27
