### ISSUE TITLE
Does Smartlook hook directly into the ui operations queue of react native?

### ISSUE THREAD

**Issue by evelant** [smartlook/smartlook-react-native-sdk#24]
I ask because this crash is plaguing my react-native app and we use Smartlook. It seems that something (likely proprietary binary code like Smartlook) is modifying the operations queue in react-native causing a crash.

https://github.com/facebook/react-native/pull/11428

**Comment by adamblack** [comment]
Hi @AndrewMorsillo ,

nope, I do not think our code somehow modifies ui operations queue. I can see you opened issue directly at RN GH: https://github.com/facebook/react-native/issues/27819

Do you think it is Smartlook related issue? If so, please create new issue in our new issue tracker: https://github.com/smartlook/smartlook-mobile-issue-tracker
