### ISSUE TITLE
error when using Smartlook

### ISSUE THREAD

**Issue by The0racle** [smartlook/smartlook-react-native-sdk#28]
This is a RN 059.10 android project. I added the react native wrapper, linked the project, and added  the package to the `getPackagesMethod` of `MainApplication.java` (see below):
```
import com.smartlook.sdk.RNSmartlookPackage;
.
.
.
protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
      // Add additional packages you require here
      // No need to add RnnPackage and MainReactPackage
      new RNSmartlookPackage()
    );
  }
```

On my `index.js` I have:

```
import Smartlook from 'smartlook-react-native-wrapper';
Smartlook.setupAndStartRecording('MY KEY');
```

When I run the app, I keep getting an error on the console: ` E/onic.androidap: Invalid ID`. I can also see printed 
```Smartlook_Smartlook: setRenderingMethod(): You have entered invalid rendering method!```

Am I missing something?

**Comment by SenNeonoveNoci** [comment]
Hi @The0racle,

`Smartlook_Smartlook: setRenderingMethod(): You have entered invalid rendering method!`

this is our mistake, it's just a harmless log that should not be called. We will fix this in a new version of the SDK. For now, you can just ignore it.

**Comment by The0racle** [comment]
@SenNeonoveNoci What about the following log? It keeps getting printed over and over again only when I use Smartlook.
```
E/onic.androidap: Invalid ID
```

**Comment by vi1199** [comment]
Hi, i'm also getting Invalid ID in android log. is there any progress ?
i'm using react native -> 0.62.2
smartlook-react-native-wrapper -> 0.28.0

**Comment by igorabiola** [comment]
Hi, i'm also getting Invalid ID in android log.
with 
react native -> 0.59.10 and 0.63.2
smartlook-react-native-wrapper -> 0.32.0
any news?

**Comment by adamblack** [comment]
Hi @The0racle , @vinny3273 , @igorabiola ,

I just tested our latest SDK with multiple RN versions and this error seems to be not reproducible on my side. Please, if this still happens, create new issue in our new tracker ( https://github.com/smartlook/smartlook-mobile-issue-tracker ). -> Would be great to also get i.e. list of other dependencies.
