### ISSUE TITLE
Black screen on webviews

### ISSUE THREAD

**Issue by moshaheen** [smartlook/smartlook-react-native-sdk#29]
Having a webview in my react native app shows as a black screen in the recordings

**Comment by adamblack** [comment]
Hi @moshaheen ,

WebView is not recorded by default however you can pass any View's ref to our API and SDK will record even blacklisted Views, i.e.:

<TextInput 
  ref={(ref) => { 
    Smartlook.unregisterBlacklistedView(ref); 
    }
  }
...
