### ISSUE TITLE
set identity in react native

### ISSUE THREAD

**Issue by moshaheen** [smartlook/smartlook-react-native-sdk#30]
I don't see how can we set identity in the smartlook react native SDK ? can we even do that ? can someone illustrate

**Comment by adamblack** [comment]
Hi @moshaheen ,

feel free to use: Smartlook.setUserIdentifier(string userIdentifier);

More info about API can be found at: https://smartlook.github.io/docs/sdk/api-reference?platform=react

**Comment by moshaheen** [comment]
I tried Smartlook.setUserIdentifier("test@test.com") but the user is still not set in the recordings dashboard when viewing this session
