### ISSUE TITLE
Possible performance issue on Android

### ISSUE THREAD

**Issue by evelant** [smartlook/smartlook-react-native-sdk#31]
I have users reporting a stutter every 500ms which seems like it might be coming from Smartlook, my app doesn't run anything on a 500ms loop. One reporting device is a Blackberry Key 1 with a Snapdragon 625 and 3gb ram, a slightly older device but I don't think it should show any stutters. We're on the latest Smartlook RN sdk. Thoughts on whether Smartlook could be the culprit here?

**Comment by adamblack** [comment]
Hi @AndrewMorsillo ,

yep, that sounds like something connected to our SDK. I created new [issue](https://github.com/smartlook/smartlook-mobile-issue-tracker/issues/3) in our official issue tracker (this one is deprecated).

Please, could you post your i.e. dependencies or which app are we talking about?
