### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by JeromeSiau** [smartlook/smartlook-react-native-sdk#4]
Hello,

We"ve just subscribed to smartlook and add it on our react native app.
We now have new errors on android caused by smartlook

React native version : 0.59.0

First one : 

> java.lang.RuntimeException: 
>   at android.app.ActivityThread.handleReceiver (ActivityThread.java:3606)
>   at android.app.ActivityThread.access$1300 (ActivityThread.java:237)
>   at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1796)
>   at android.os.Handler.dispatchMessage (Handler.java:106)
>   at android.os.Looper.loop (Looper.java:214)
>   at android.app.ActivityThread.main (ActivityThread.java:7045)
>   at java.lang.reflect.Method.invoke (Native Method)
>   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
> Caused by: java.lang.IllegalStateException: 
>   at com.smartlook.sdk.smartlook.analytics.receiver.ReferrerReceiver.onReceive (SourceFile:16)
>   at android.app.ActivityThread.handleReceiver (ActivityThread.java:3597)

with already 5 crashes for 5 users after just a few hours.

2nd one : 

> java.lang.RuntimeException: 
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:832)
> Caused by: java.lang.reflect.InvocationTargetException: 
>   at java.lang.reflect.Method.invoke (Native Method)
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:942)
> Caused by: java.io.IOException: 
>   at java.io.UnixFileSystem.createFileExclusively0 (Native Method)
>   at java.io.UnixFileSystem.createFileExclusively (UnixFileSystem.java:280)
>   at java.io.File.createNewFile (File.java:948)
>   at com.smartlook.sdk.smartlook.c.e.a (SourceFile:89)
>   at com.smartlook.sdk.smartlook.analytics.d.a (SourceFile:334)
>   at com.smartlook.sdk.smartlook.analytics.c.a (SourceFile:243)
>   at com.smartlook.sdk.smartlook.a.a.b.a (SourceFile:117)
>   at com.smartlook.sdk.smartlook.a.a.b.a (SourceFile:13)
>   at com.smartlook.sdk.smartlook.a.a.b$f.a (SourceFile:96)
>   at com.smartlook.sdk.smartlook.a.a.b$f.a (SourceFile:93)
>   at com.smartlook.sdk.smartlook.a.a.onResponse (SourceFile:12)
>   at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run (ExecutorCallAdapterFactory.java:71)
>   at android.os.Handler.handleCallback (Handler.java:761)
>   at android.os.Handler.dispatchMessage (Handler.java:98)
>   at android.os.Looper.loop (Looper.java:156)
>   at android.app.ActivityThread.main (ActivityThread.java:6523)

but only one user had this issue.
How can we fixed this errors ?

Thx
Jerome

**Comment by adamblack** [comment]
Hi @Jerome38 ,

thanks for the info. Should be fixed in new version.
